-- DB-001: Lock down SECURITY DEFINER functions with explicit search_path
-- DB-002: Enable RLS on deletion_eligibility_checks
-- DB-003: Enable RLS on school_creation_requests
-- DB-013/014: Tighten overly-broad RLS on conversations/messages/staff_id_sequences
-- Generated by audit 2026-06-08

-- DB-001: Force search_path on user_class_ids and reserve_staff_id
-- Idempotent: drop + recreate with safe search_path
CREATE OR REPLACE FUNCTION public.user_class_ids()
RETURNS uuid[]
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT COALESCE(array_agg(class_id), ARRAY[]::uuid[])
  FROM public.class_teachers
  WHERE staff_profile_id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION public.user_wing_ids()
RETURNS uuid[]
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT COALESCE(array_agg(wing_id), ARRAY[]::uuid[])
  FROM public.wings_coordinators
  WHERE staff_id = auth.uid();
$$;

-- CQ-048: Legacy verify_pin SQL function removed.
-- Use supabase.functions.invoke('verify-pin') instead — edge function
-- implements PBKDF2-SHA256 (210k iters) via Web Crypto API.

-- DB-002: Enable RLS on deletion_eligibility_checks
ALTER TABLE public.deletion_eligibility_checks ENABLE ROW LEVEL SECURITY;

-- Only service role can write; principal/superadmin can read for their school context
DROP POLICY IF EXISTS "deletion_eligibility_checks_select" ON public.deletion_eligibility_checks;
CREATE POLICY "deletion_eligibility_checks_select"
  ON public.deletion_eligibility_checks FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role IN ('superadmin', 'principal', 'master_admin')
    )
  );

DROP POLICY IF EXISTS "deletion_eligibility_checks_write" ON public.deletion_eligibility_checks;
-- No write policy: writes happen via SECURITY DEFINER functions only

-- DB-003: Enable RLS on school_creation_requests
ALTER TABLE public.school_creation_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "school_creation_requests_superadmin" ON public.school_creation_requests;
CREATE POLICY "school_creation_requests_superadmin"
  ON public.school_creation_requests FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'superadmin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'superadmin'
    )
  );

-- DB-014: Lock down staff_id_sequences to service_role only (called by edge function)
DROP POLICY IF EXISTS "staff_id_sequences_all" ON public.staff_id_sequences;
-- No replacement policy: edge function uses service_role, RLS bypassed by service role key
-- Authenticated users have no access

-- DB-013: Tighten conversations + messages RLS to require participant membership
DROP POLICY IF EXISTS "conversations_select" ON public.conversations;
CREATE POLICY "conversations_select"
  ON public.conversations FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.conversation_participants cp
      WHERE cp.conversation_id = conversations.id
        AND cp.profile_id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'superadmin'
    )
  );

DROP POLICY IF EXISTS "conversations_insert" ON public.conversations;
CREATE POLICY "conversations_insert"
  ON public.conversations FOR INSERT
  TO authenticated
  WITH CHECK (created_by = auth.uid());

DROP POLICY IF EXISTS "conversations_update" ON public.conversations;
CREATE POLICY "conversations_update"
  ON public.conversations FOR UPDATE
  TO authenticated
  USING (created_by = auth.uid())
  WITH CHECK (created_by = auth.uid());

DROP POLICY IF EXISTS "messages_select" ON public.messages;
CREATE POLICY "messages_select"
  ON public.messages FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.conversation_participants cp
      WHERE cp.conversation_id = messages.conversation_id
        AND cp.profile_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "messages_insert" ON public.messages;
CREATE POLICY "messages_insert"
  ON public.messages FOR INSERT
  TO authenticated
  WITH CHECK (
    sender_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.conversation_participants cp
      WHERE cp.conversation_id = messages.conversation_id
        AND cp.profile_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "conversation_participants_select" ON public.conversation_participants;
CREATE POLICY "conversation_participants_select"
  ON public.conversation_participants FOR SELECT
  TO authenticated
  USING (
    profile_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.conversation_participants cp2
      WHERE cp2.conversation_id = conversation_participants.conversation_id
        AND cp2.profile_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "conversation_participants_insert" ON public.conversation_participants;
CREATE POLICY "conversation_participants_insert"
  ON public.conversation_participants FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.conversations c
      WHERE c.id = conversation_participants.conversation_id
        AND c.created_by = auth.uid()
    )
    OR profile_id = auth.uid()
  );

DROP POLICY IF EXISTS "conversation_reads_select" ON public.conversation_reads;
CREATE POLICY "conversation_reads_select"
  ON public.conversation_reads FOR SELECT
  TO authenticated
  USING (profile_id = auth.uid());

DROP POLICY IF EXISTS "conversation_reads_insert" ON public.conversation_reads;
CREATE POLICY "conversation_reads_insert"
  ON public.conversation_reads FOR INSERT
  TO authenticated
  WITH CHECK (profile_id = auth.uid());
